---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-sts
  namespace: {{ .Release.Name }}
  labels: 
    {{- include "unchained.statefulsetLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}-svc
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:   
      {{- include "unchained.statefulsetLabels" . | nindent 6 }}
  podManagementPolicy: 'Parallel'
  updateStrategy:
    type: 'RollingUpdate'
  template:
    metadata:
      namespace: {{ .Release.Name }}
      labels:
        {{- include "unchained.statefulsetLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      {{- range .Values.statefulset.containers }}
      - name: {{ .name }}
        image: {{ .image }}
        command: 
          - '/init.sh'
        {{- with .env }}
        env: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .ports }}
        ports: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- with .limits }}
          limits:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .requests }}
          requests:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        startupProbe:
          failureThreshold: 60
          periodSeconds: 30
          timeoutSeconds: 10 
          {{- if or (eq .name "daemon") (eq .name "timescaledb") }}
          exec:
            {{- if eq .name "daemon" }}
            command: 
            - '/startup.sh'
            {{- else if eq .name "timescaledb" }}
            command:
            - 'pg_isready'
            - '-U'
            - '$(POSTGRES_USER)'
            {{- end }}
          {{- else }}
          tcpSocket:
            port: 8080
          {{- end }}
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
          {{- if or (eq .name "daemon") (eq .name "timescaledb") }}
          exec:
            {{- if eq .name "daemon" }}
            command: 
            - '/liveness.sh'
            {{- else if eq .name "timescaledb" }}
            command:
            - 'pg_isready'
            - '-U'
            - '$(POSTGRES_USER)'
            {{- end }}
          {{- else }}
          tcpSocket:
            port: 8080
          {{- end }}
        readinessProbe:
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 10
          exec:
            {{- if or (eq .name "daemon") (eq .name "indexer") }}
            command: 
            - '/readiness.sh'
            {{- else }}
            command:
            - 'pg_isready'
            - '-U'
            - '$(POSTGRES_USER)'
            {{- end }}
        volumeMounts:
        - name: {{ $.Chart.Name }}-{{ .name }}-data
          mountPath: {{ default "/data" .dataDir }}
        - name: {{ $.Values.name }}
          mountPath: '/init.sh'
          subPath: {{ .name }}-init.sh
        - name: {{ $.Values.name }}
          mountPath: '/readiness.sh'
          subPath: {{ .name }}-readiness.sh
        {{- if eq .name "daemon" }}
        - name: {{ $.Values.name }}
          mountPath: '/startup.sh'
          subPath: {{ .name }}-startup.sh
        - name: {{ $.Values.name }}
          mountPath: '/liveness.sh'
          subPath: {{ .name }}-liveness.sh
        - name: {{ $.Values.name }}
          mountPath: '/tendermint.sh'
          subPath: 'tendermint.sh'
        {{- else if eq .name "indexer" }}
        - name: {{ $.Values.name }}
          mountPath: '/config.json'
          subPath: 'indexer-config.json'
        {{- else }}
        - name: dshm
          mountPath: '/dev/shm'
        {{- end }}
      {{- end }}
      volumes:
        - name: {{ .Values.name }}
          configMap:
            name: {{ .Chart.Name }}-scripts
            defaultMode: 0775
        - name: 'dshm'
          emptyDir: 
            medium: 'Memory'
            sizeLimit: 1Gi
  volumeClaimTemplates:
  {{- range .Values.statefulset.containers }}
  - metadata:
      name: {{ $.Chart.Name }}-{{ .name }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $.Values.global.storageClassName }}
      resources:
        requests:
          storage: {{ .storage_size }}
  {{- end }}