{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "midgard.serviceAccountName" . }}
  labels:
{{ include "midgard.labels" . | nindent 4 }}
{{- end -}}
