apiVersion: v2
name: arkeo-stack
description: Deploys a Arkeo stack with options to enable or disable some services
type: application
version: 0.1.0

appVersion: 0.1.0

dependencies:
  - name: gateway
    repository: file://../gateway
    version: 0.1.0
    condition: gateway.enabled

  - name: arkeo
    repository: file://../arkeo
    version: 0.1.0
    condition: arkeo.enabled

  - name: sentinel
    repository: file://../sentinel
    version: 0.1.0
    condition: sentinel.enabled

  - name: unchained-stack
    repository: file://../unchained
    version: 1.0.0
    condition: unchained.enabled
