apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkeo.fullname" . }}
  labels:
    {{- include "arkeo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "arkeo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arkeo.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "arkeo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      initContainers:
      - name: init-external-ip
        image: alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}
        {{- if .Values.global.gateway.enabled }}
        command:
        - /bin/sh
        - -c
        - |
          if [ -f /root/.arkeo/setup-completed ]; then
            echo "Setup already completed. Skipping init container."
            exit 0
          fi
          
          echo "Running initial setup..."
          /scripts/setup-testnet.sh false '{{ .Values.global.gateway.name }}' '{{ include "arkeo.fullname" . }}-setup-testnet'
          touch /root/.arkeo/setup-completed
        {{- else }}
        command:
        - /bin/sh
        - -c
        - |
          if [ -f /root/.arkeo/setup-completed ]; then
            echo "Setup already completed. Skipping init container."
            exit 0
          fi
          
          echo "Running initial setup..."
          /scripts/setup-testnet.sh false '{{ include "arkeo.fullname" . }}' '{{ include "arkeo.fullname" . }}-setup-testnet'
          touch /root/.arkeo/setup-completed
        {{- end }}
        env:
        - name: CHAIN_ID
          value: "{{ .Values.chainID.mainnet }}"
        - name: MONIKER
          value: "{{ .Values.arkeo.moniker }}"
        - name: WALLET_NAME
          value: "{{ .Values.arkeo.wallet }}"
        - name: FEES
          value: "{{ .Values.arkeo.fees }}"
        - name: AMOUNT
          value: "{{ .Values.arkeo.amount }}"
        - name: MNEMONIC
          valueFrom:
            secretKeyRef:
              name: arkeo-mnemonic
              key: mnemonic
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: arkeo-data
          mountPath: /root/.arkeo

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "arkeo.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - arkeod
            - start
            - --pruning
            - nothing
            - --minimum-gas-prices
            - 0.0001uarkeo
            - --home
            - /root/.arkeo
          volumeMounts:
            - name: arkeo-data
              mountPath: /root/.arkeo
            - name: scripts
              mountPath: /kube-scripts/
            - name: tmp
              mountPath: /tmp  
          ports:
            - name: api
              containerPort: {{ .Values.service.port.api }}
              protocol: TCP
            - name: p2p
              containerPort: {{ include "arkeo.p2p" . }}
              protocol: TCP
            - name: rpc
              containerPort: {{ include "arkeo.rpc" . }}
              protocol: TCP
            - name: prometheus
              containerPort: 26660
              protocol: TCP
          livenessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /status
              port: rpc
          startupProbe:
            failureThreshold: 30
            timeoutSeconds: 10
            httpGet:
              path: /status
              port: rpc
          readinessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /status
              port: rpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if eq .Values.type "validator" }}
        - name: validator-setup
          image: alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}
          command:
            - /bin/sh
            - -c
            - |
              if [ -f /root/.arkeo/validator-setup-completed ]; then
                echo "Validator setup already completed. Skipping."
                exit 0
              fi

              # Wait for node RPC to be ready
              until curl -s http://localhost:26657/status | grep -q '"catching_up":false'; do
                echo "Waiting for the node to fully start..."
                sleep 5
              done
              echo "Node is up. Proceeding with validator creation."
              chmod +x /scripts/validator.sh
              /scripts/validator.sh
              
              echo "Validator setup complete. Exiting."
              touch /root/.arkeo/validator-setup-completed
              exit 0
          volumeMounts:
            - name: arkeo-data
              mountPath: /root/.arkeo
            - name: scripts
              mountPath: /scripts
          env:
            - name: CHAIN_ID
              value: "{{ .Values.chainID.mainnet }}"
            - name: MONIKER
              value: "{{ .Values.arkeo.moniker }}"
            - name: WALLET_NAME
              valueFrom:
                secretKeyRef:
                  name: arkeo-wallet
                  key: wallet
            - name: FEES
              value: "{{ .Values.arkeo.fees }}"
            - name: AMOUNT
              value: "{{ .Values.arkeo.amount }}"
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: arkeo-mnemonic
                  key: mnemonic
          {{- end }}
      volumes:
        - name: arkeo-data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "arkeo.fullname" . }}{{- end }}
        - name: tmp
          emptyDir: {} 
        - name: data
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ include "arkeo.fullname" . }}-scripts
            defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
