{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arkeo.serviceAccountName" . }}
  labels:
{{ include "arkeo.labels" . | nindent 4 }}
{{- end -}}
