---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Name }}
  labels:
    name: "ipfs"
    nodeType: "cluster"
spec:
  type: ClusterIP
  ports:
  {{- range $nodeName, $ports := .Values.ports }}
  {{- range $portIndex, $port := $ports }}
  - name: {{ $port.name }}
    port: {{ $port.containerPort }}
    targetPort: {{ $port.name }}
  {{- end }}
  {{- end }}
  selector:
    name: "ipfs"
    nodeType: "cluster"