---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-sts
  namespace: {{ .Release.Name }}
  labels: 
    name: "ipfs"
    nodeType: "cluster"
spec:
  serviceName: {{ .Chart.Name }}-svc
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:   
      name: "ipfs"
      nodeType: "cluster"
  podManagementPolicy: 'Parallel'
  updateStrategy:
    type: 'RollingUpdate'
  template:
    metadata:
      namespace: {{ .Release.Name }}
      labels:
        name: "ipfs"
        nodeType: "cluster"
    spec:
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: "configure-ipfs"
        image: "ipfs/go-ipfs:latest"
        command: 
        - 'sh'
        - '/custom/configure-ipfs.sh'
        volumeMounts:
        - name: "ipfs-storage"
          mountPath: "/data/ipfs"
        - name: "configure-scripts"
          mountPath: "/custom"
      containers: 
      - name: {{ Chart.name }}-ipfs
        image: {{ .Values.image.ipfs }}
        {{- with .Values.env.ipfs }}
        env: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ports.ipfs }}
        ports: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- with .Values.limits.ipfs }}
          limits:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
          tcpSocket:
            port: 'swarm'
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{-end }}
      - name: {{ Chart.name }}-ipfs-cluster
        image: {{ .Values.image.ipfsCluster }}
#        {{- with .Values.env.ipfsCluster }}
#        env: 
#          {{- toYaml . | nindent 10 }}
#        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-scripts
        {{- with .Values.ports.ipfsCluster }}
        ports: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- with .Values.limits.ipfsCluster }}
          limits:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        command: {{- toYaml .Values.command.ipfsCluster | nindent 10 }} 
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          tcpSocket:
            port: 'cluster-swarm'
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{-end }}
      volumes:
        - name: 'configure-script'
          configMap:
            name: {{ .Chart.Name }}-scripts
            defaultMode: 0775
  volumeClaimTemplates:
  - metadata:
      name: 'cluster-storage'
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $.Values.global.storageClassName }}
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: 'ipfs-storage'
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $.Values.global.storageClassName }}
      resources:
        requests:
          storage: 200Gi