name: ethereum

api:
  tier: api
  image: "shapeshiftdao/unchained-ethereum-api:latest"
  autoscaling: true
  replicas: 1
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi
  env:
  - name: INDEXER_URL
    value: "http://ethereum-svc.unchained.svc.cluster.local:8001"
  - name: INDEXER_WS_URL
    value: "ws://ethereum-svc.unchained.svc.cluster.local:8001/websocket"
  - name: LOG_LEVEL
    value: "debug"
  - name: NETWORK
    value: "mainnet"
  - name: RPC_URL
    value: "http://ethereum-svc.unchained.svc.cluster.local:8545"

statefulset:
  name: ethereum
  replicas: 1
  containers:
    - name: daemon
      image: "ethereum/client-go:v1.13.5"
      command: 
        - '/init.sh' 
      limits:
        cpu: 2
        memory: 24Gi
      requests:
        cpu: 1
      ports:
      - name: daemon-rpc
        containerPort: 8545
      - name: daemon-ws
        containerPort: 8546
      - name: daemon-beacon
        containerPort: 8551
      storage_size: 1250Gi
      env:
      - name: NETWORK
        value: mainnet
    - name: daemon-beacon
      image: "gcr.io/prysmaticlabs/prysm/beacon-chain:v4.1.1"
      args:
        - '--datadir'
        - '/data'
        - '--execution-endpoint'
        - 'http://localhost:8551'
        - '--jwt-secret'
        - '/jwt.hex'
        - '--accept-terms-of-use'
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1
      storage_size: 500Gi
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:559cfbc"
      command: 
        - '/bin/blockbook'
        - '-blockchaincfg=/config.json'
        - '-datadir=/data'
        - '-sync'
        - '-public=:8001'
        - '-enablesubnewtx'
        - '-logtostderr'
        - '-dbcache=268435456'
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1
      storage_size: 500Gi
      ports:
      - name: indexer
        containerPort: 8001