apiVersion: v1
kind: Service
metadata:
  name: {{ include "binance-smart-daemon.fullname" . }}
  labels:
    {{- include "binance-smart-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "binance-smart-daemon.selectorLabels" . | nindent 4 }}
