name: bnbsmartchain

api:
  tier: api
  image: "shapeshiftdao/unchained-bnbsmartchain-api:latest"
  autoscaling: true
  replicas: 1
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
  env:
  - name: INDEXER_URL
    value: "http://bnbsmartchain-svc.unchained.svc.cluster.local:8001"
  - name: INDEXER_WS_URL
    value: "ws://bnbsmartchain-svc.unchained.svc.cluster.local:8001/websocket"
  - name: LOG_LEVEL
    value: "debug"
  - name: NETWORK
    value: "mainnet"
  - name: RPC_URL
    value: "http://bnbsmartchain-svc.unchained.svc.cluster.local:8545"

statefulset:
  name: bnbsmartchain
  replicas: 1
  containers:
    - name: daemon
      image: "shapeshiftdao/bnb-smart-chain:v1.3.5"
      env:
      - name: SNAPSHOT
        value: 'https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20231211.tar.lz4'
      command: 
        - '/init.sh' 
      limits:
        cpu: 16
        memory: 72Gi
      requests:
        cpu: 8
      ports:
      - name: daemon-rpc
        containerPort: 8545
      - name: daemon-ws
        containerPort: 8546
      storage_size: 5500Gi
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:559cfbc"
      command: 
        - '/bin/blockbook'
        - '-blockchaincfg=/config.json'
        - '-datadir=/data'
        - '-sync'
        - '-public=:8001'
        - '-enablesubnewtx'
        - '-logtostderr'
        - '-workers=1'
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 2
      storage_size: 1000Gi
      ports:
      - name: indexer
        containerPort: 8001