apiVersion: v2
name: unchained-stack
description: Deploys an Unchained stack with options to enable or disable some services
type: application
version: 1.0.0

appVersion: 1.0.0

dependencies:
- name: arbitrum
  version: "1.0.0"
  repository: file://./charts/arbitrum
  condition: arbitrum.enabled
- name: avalanche
  version: "1.0.0"
  repository: file://./charts/avalanche
  condition: avalanche.enabled
- name: bitcoin
  version: "1.0.0"
  repository: file://./charts/bitcoin
  condition: bitcoin.enabled
- name: bitcoincash
  version: "1.0.0"
  repository: file://./charts/bitcoincash
  condition: bitcoincash.enabled
- name: bnbsmartchain
  version: "1.0.0"
  repository: file://./charts/bnbsmartchain
  condition: bnbsmartchain.enabled
- name: cosmos
  version: "1.0.0"
  repository: file://./charts/cosmos
  condition: cosmos.enabled
- name: dogecoin
  version: "1.0.0"
  repository: file://./charts/dogecoin
  condition: dogecoin.enabled
- name: gnosis
  version: "1.0.0"
  repository: file://./charts/gnosis
  condition: gnosis.enabled
- name: litecoin
  version: "1.0.0"
  repository: file://./charts/litecoin
  condition: litecoin.enabled
- name: ethereum
  version: "1.0.0"
  repository: file://./charts/ethereum
  condition: ethereum.enabled
- name: optimism
  version: "1.0.0"
  repository: file://./charts/optimism
  condition: optimism.enabled
- name: polygon
  version: "1.0.0"
  repository: file://./charts/polygon
  condition: polygon.enabled
- name: thorchain
  version: "1.0.0"
  repository: file://./charts/thorchain
  condition: thorchain.enabled
