apiVersion: v2
name: unchained-stack
description: Deploys an Unchained stack with options to enable or disable some services
type: application
version: 1.0.0

appVersion: 1.0.0

dependencies:
- name: avalanche
  version: "1.0.0"
  repository: file://infra/unchained/chart/avalanche
  condition: avalanche.enabled
- name: bitcoin
  version: "1.0.0"
  repository: file://infra/unchained/chart/bitcoin
  condition: bitcoin.enabled
- name: bitcoincash
  version: "1.0.0"
  repository: file://infra/unchained/chart/bitcoin-cash
  condition: bitcoincash.enabled
- name: bnbsmartchain
  version: "1.0.0"
  repository: file://infra/unchained/chart/bnbsmartchain
  condition: bnbsmartchain.enabled
- name: cosmos
  version: "1.0.0"
  repository: file://infra/unchained/chart/cosmos
  condition: cosmos.enabled
- name: dogecoin
  version: "1.0.0"
  repository: file://infra/unchained/chart/dogecoin
  condition: dogecoin.enabled
- name: gnosis
  version: "1.0.0"
  repository: file://infra/unchained/chart/gnosis
  condition: gnosis.enabled
- name: litecoin
  version: "1.0.0"
  repository: file://infra/unchained/chart/litecoin
  condition: litecoin.enabled
- name: ethereum
  version: "1.0.0"
  repository: file://infra/unchained/chart/ethereum
  condition: ethereum.enabled
- name: optimism
  version: "1.0.0"
  repository: file://infra/unchained/chart/optimism
  condition: optimism.enabled
- name: polygon
  version: "1.0.0"
  repository: file://infra/unchained/chart/polygon
  condition: polygon.enabled
- name: thorchain
  version: "1.0.0"
  repository: file://infra/unchained/chart/thorchain
  condition: thorchain.enabled
- name: ipfs
  version: "1.0.0"
  repository: file://infra/unchained/chart/ipfs
  condition: ipfs.enabled
