global:
  backupSchedule: "0 4 * * 0"
  backupCount: "3"
  storageClassName: "microk8s-hostpath"

etherscan_api_key: ""

avalanche: 
  enabled: false

bitcoin:
  enabled: false

bitcoincash:
  enabled: false

bnbsmartchain:
  enabled: false

cosmos:
  enabled: false

dogecoin:
  enabled: true

ethereum:
  enabled: true

gnosis:
  enabled: false

litecoin:
  enabled: true

optimism:
  enabled: false

polygon:
  enabled: false

thorchain:
  enabled: true

ipfs:
  enabled: false