global:
  backupSchedule: 0 4 * * 0
  backupCount: '3'
etherscan_api_key: ''
arbitrum:
  enabled: false
avalanche:
  enabled: false
bitcoin:
  enabled: true
bitcoincash:
  enabled: false
bnbsmartchain:
  enabled: false
cosmos:
  enabled: false
dogecoin:
  enabled: false
ethereum:
  enabled: true
gnosis:
  enabled: false
litecoin:
  enabled: false
optimism:
  enabled: false
osmosis:
  enabled: false
polygon:
  enabled: false
thorchain:
  enabled: false
