---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Name }}
data: 
  init.sh: |
    #!/bin/sh

    #initialize the relayer config file
      rly config init

    #add the chains to the config
      rly chains add --file /arkeo.json {{ .Values.src_chain.name }}
      rly chains add {{ .Values.dst_chain.name }} --testnet

    #add new keys
      rly keys restore {{ .Values.src_chain.name }} {{ .Values.src_chain.keyname }} "{{ .Values.mnemonic.arkeo }}"
      rly keys restore {{ .Values.dst_chain.name }} {{ .Values.dst_chain.keyname }} "{{ .Values.mnemonic.osmo }}"

    #set keys as default 
      rly keys use {{ .Values.src_chain.name }} {{ .Values.src_chain.keyname }}
      rly keys use {{ .Values.dst_chain.name }} {{ .Values.dst_chain.keyname }}

    #query balance
      rly q balance {{ .Values.src_chain.name }}
      rly q balance {{ .Values.dst_chain.name }}

    #create path
      rly paths new arkeo osmo-test-5 {{ .Values.pathname }}

    #create client, connection, channel
      rly tx link {{ .Values.pathname }} -d

    
  
  arkeo.json: |
    {
      "type": "cosmos",
      "value": {
        "key": "testkey",
        "chain-id": "arkeo",
        "rpc-addr": "http://arkeo.arkeo-testnet.svc.cluster.local:26657",
        "grpc-addr": "",
        "account-prefix": "tarkeo",
        "keyring-backend": "test",
        "gas-adjustment": 1.5,
        "gas-prices": "0.025uarkeo",
        "debug": true,
        "timeout": "10s",
        "output-format": "json",
        "sign-mode": "direct"
      }
    }
 
