---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Chart.Name }}
  labels:
    {{- include "relayer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "relayer.labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      namespace: {{ .Release.Name }}
      labels: 
        {{- include "relayer.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command: 
        - 'rly'
        - 'config'
        - 'init'