replicas: 3

image: 
  ipfs: "ipfs/go-ipfs:latest"
  ipfsCluster: "ipfs/ipfs-cluster:latest"

env:
  ipfs:
  - name: "IPFS_FD_MAX"
    value: "8192"
  ipfsCluster:
  - name: "CLUSTER_ID"
    valueFrom: 
      configMapKeyRef: 
        name: "ipfs-scripts"
        key: "cluster-id"
  - name: "CLUSTER_PRIVATEKEY"
    valueFrom: 
      secretKeyRef: 
        name: "ipfs-secret"
        key: "cluster-priv-key"
  - name: "CLUSTER_SECRET"
    valueFrom: 
      secretKeyRef: 
        name: "ipfs-secret"
        key: "cluster-secret"
  - name: "CLUSTER_MONITOR_PING_INTERVAL"
    value: "3m"
  - name: "SVC_NAME"
    value: "ipfs-svc"

ports:
  ipfs:
  - name: "swarm"
    containerPort: 4001
    protocol: "TCP"
  - name: "swarm-udp"
    containerPort: 4002
    protocol: "UDP"
  - name: "api"
    containerPort: 5001
    protocol: "TCP"
  - name: "ws" 
    containerPort: 8081
    protocol: "TCP"
  - name: "http" 
    containerPort: 8080
    protocol: "TCP"
  ipfsCluster:
  - name: "api-http"
     containerPort: 9094
     protocol: "TCP"
  - name: "proxy-http"
    containerPort: 9095
    protocol: "TCP"
  - name: "cluster-swarm"
    containerPort: 9096
    protocol: "TCP"

limits:
  ipfs:
    cpu: '250m'
    memory: '512Mi'
  ipfsCluster:
    cpu: '100m'
    memory: '128Mi'

command: 
  ipfsCluster:
  - 'sh'
  - '/custom/entrypoint.sh'

volumeMounts: 
- name: "ipfs-storage"
  mountPath: "/data/ipfs"
- name: "configure-script"
  mountPath: "/custom"