replicas: 1

clusterSecret: ""
clusterPrivKey: ""

image: 
  ipfs: "ipfs/go-ipfs:latest"
  ipfsCluster: "ipfs/ipfs-cluster:latest"

env:
  ipfs:
  - name: "IPFS_FD_MAX"
    value: "8192"
  ipfsCluster:
  - name: "CLUSTER_MONITOR_PING_INTERVAL"
    value: "3m"
  - name: "SVC_NAME"
    value: "ipfs-svc"

limits:
  ipfs:
    cpu: '250m'
    memory: '512Mi'
  ipfsCluster:
    cpu: '100m'
    memory: '128Mi'

volumeMounts: 
- name: "ipfs-storage"
  mountPath: "/data/ipfs"
- name: "configure-script"
  mountPath: "/custom"
