replicas: 3

clusterSecret: ""
clusterPrivKey: ""

image: 
  ipfs: "ipfs/go-ipfs:latest"
  ipfsCluster: "ipfs/ipfs-cluster:latest"

env:
  ipfs:
  - name: "IPFS_FD_MAX"
    value: "8192"
  ipfsCluster:
  - name: "CLUSTER_ID"
    valueFrom: 
      configMapKeyRef: 
        name: "ipfs-scripts"
        key: "cluster-id"
  - name: "CLUSTER_PRIVATEKEY"
    valueFrom: 
      secretKeyRef: 
        name: "ipfs-secret"
        key: "cluster-priv-key"
  - name: "CLUSTER_SECRET"
    valueFrom: 
      secretKeyRef: 
        name: "ipfs-secret"
        key: "cluster-secret"
  - name: "CLUSTER_MONITOR_PING_INTERVAL"
    value: "3m"
  - name: "SVC_NAME"
    value: "ipfs-svc"

