name: bnbsmartchain

api:
  tier: api
  image: "shapeshiftdao/unchained-bnbsmartchain-api:latest"
  autoscaling: true
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
  env:
  - name: INDEXER_URL
    value: "https://dev-indexer.bnbsmartchain.shapeshift.com"
  - name: INDEXER_WS_URL
    value: "wss://dev-indexer.bnbsmartchain.shapeshift.com/websocket"
  - name: LOG_LEVEL
    value: "debug"
  - name: NETWORK
    value: "mainnet"
  - name: RPC_URL
    value: "https://dev-daemon.bnbsmartchain.shapeshift.com"

statefulset:
  name: bnbsmartchain
  replicas: 2
  containers:
    - name: daemon
      image: "shapeshiftdao/bnb-smart-chain:v1.2.11"
      command: 
        - '/init.sh' 
      limits:
        cpu: 8
        memory: 72Gi
      requests:
        cpu: 4
        memory: 48Gi
      ports:
      - name: daemon-rpc
        containerPort: 8545
      - name: daemon-ws
        containerPort: 8546
      storage_size: 4500Gi
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:95ee9b5"
      command: 
        - '/bin/blockbook'
        - '-blockchaincfg=/config.json'
        - '-datadir=/data'
        - '-sync'
        - '-public=:8001'
        - '-enablesubnewtx'
        - '-logtostderr'
      limits:
        cpu: 4
        memory: 24Gi
      requests:
        cpu: 2
      storage_size: 1000Gi
      ports:
      - name: indexer
        containerPort: 8001