name: gnosis

api:
  tier: api
  image: "shapeshiftdao/unchained-gnosis-api:latest"
  replicas: 1
  autoscaling: true
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 500m
    memory: 250Mi
  env:
  - name: INDEXER_URL
    value: "http://gnosis-svc.unchained.svc.cluster.local:8001"
  - name: INDEXER_WS_URL
    value: "ws://gnosis-svc.unchained.svc.cluster.local:8001/websocket"
  - name: LOG_LEVEL
    value: "debug"
  - name: NETWORK
    value: "mainnet"
  - name: RPC_URL
    value: "http://gnosis-svc.unchained.svc.cluster.local:8545"

statefulset:
  name: gnosis
  replicas: 1
  containers:
    - name: daemon
      image: "nethermind/nethermind:1.23.0"
      command: 
        - '/init.sh'
      ports:
      - name: daemon-rpc
        containerPort: 8545
      - name: daemon-ws
        containerPort: 8546
      - name: daemon-beacon
        containerPort: 8551
      limits:
        cpu: 2
        memory: 6Gi
      requests:
        cpu: 2
      storage_size: 1000Gi
    - name: daemon-beacon
      image: "sigp/lighthouse:v4.5.0"
      command: 
        - '/usr/local/bin/lighthouse'
        - 'beacon_node'
        - '--network=gnosis'
        - '--disable-upnp'
        - '--datadir=/data'
        - '--http'
        - '--execution-endpoint=http://localhost:8551'
        - '--execution-jwt=/jwt.hex'
        - '--checkpoint-sync-url=https://checkpoint.gnosischain.com/'
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 1
      storage_size: 500Gi
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:gnosis-f21acf1"
      command: 
        - '/bin/blockbook'
        - '-blockchaincfg=/config.json'
        - '-datadir=/data'
        - '-sync'
        - '-public=:8001'
        - '-enablesubnewtx'
        - '-logtostderr'
        - '-dbcache=268435456'
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1
      storage_size: 500Gi
      ports:
      - name: indexer
        containerPort: 8001