name: dogecoin

api:
  tier: api
  image: "shapeshiftdao/unchained-dogecoin-api:latest"
  autoscaling: true
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi
  env:
  - name: INDEXER_URL
    value: "https://dev-indexer.dogecoin.shapeshift.com"
  - name: INDEXER_WS_URL
    value: "wss://dev-indexer.dogecoin.shapeshift.com/websocket"
  - name: LOG_LEVEL
    value: "debug"
  - name: NETWORK
    value: "mainnet"
  - name: RPC_URL
    value: "https://user:password@dev-daemon.dogecoin.shapeshift.com"

statefulset: 
  name: dogecoin
  replicas: 2
  containers:
    - name: daemon
      image: "shapeshiftdao/dogecoin:1.14.6"
      command: 
        - '/init.sh' 
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1
      ports:
      - name: daemon-rpc
        containerPort: 8332
      env:
      - name: NETWORK
        value: mainnet
      storage_size: 250Gi
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:95ee9b5"
      command: 
        - '/bin/blockbook'
        - '-blockchaincfg=/config.json'
        - '-datadir=/data'
        - '-sync'
        - '-public=:8001'
        - '-enablesubnewtx'
        - '-logtostderr'
        - '-workers=1'
      limits:
        cpu: 2
        memory: 16Gi
      requests:
        cpu: 1
      storage_size: 250Gi
      ports:
      - name: indexer
        containerPort: 8001